#
# Makefile for PyWENO documentation
#

#SPHINXBUILD = python /usr/local/bin/sphinx-build
SPHINXBUILD = sphinx-build
SPHINXOPTS  = -d _doctrees

html:
	$(SPHINXBUILD) -a -b html $(SPHINXOPTS) . _build

all: html

.PHONY: html
