#
# Makefile for PyWENO documentation
#

SPHINXBUILD = /home/memmett/venv/mpich2/bin/python /usr/local/bin/sphinx-build
SPHINXOPTS  = -d _doctrees

html:
	$(SPHINXBUILD) -a -b html $(SPHINXOPTS) . _build

all: html

.PHONY: html
